### ISSUE TITLE
Convert -9999 nulls to Null after exporting feature class

### ISSUE THREAD

**Issue by nickrsan** [ucd-cws/arcproject-wq-processing#31]
The mapping code uses some of the code Andy made for casting the numpy data to feature class compatibility. We should convert -9999s back to Nones after export (and confirm we can't just pass in None originally first if we use a geodatabase).

**Comment by andybell** [comment]
The numpy array can't handle the null data. -9999 is used as a placeholder when converting the numpy array to a feature class. I added in a function in query_to_feature() that trys to convert all -9999s back to <Null> if the layer in a gdb. If the export layer requested is a shp then the no data values will remain as -9999.
