### ISSUE TITLE
Questions for John

### ISSUE THREAD

**Issue by nickrsan** [ucd-cws/arcproject-wq-processing#35]
- [x] State Plane Projection - Meters or Feet?
- [x] Difference between "WQT" and "WQP"

**Comment by andybell** [comment]
Some additional questions about the gain files
- [ ] Site IDs with HIGH and LOW (Feb 2016)
- [ ] Profiles with no records within the top 1m of depth profile 
- [ ] For each site, vert profiles taken at various locations  depending on sample day. Average location for linear reference?

**Comment by andybell** [comment]
Additional data to get - standardized reference lines for all sloughs (for linear reference), standardized name + abbreviations for all sloughs (add to sites table)

**Comment by nickrsan** [comment]
- [ ] `main` calls the matching code, which causes about 5% of records to be lost - thus the 934 vs 977 records. The unittest doesn't perform the match, so data isn't lost. Probably worth consulting John about the lost data - I imagine it's a consequence they dealt with previously?
