### ISSUE TITLE
Incorporate DST adjustment into the join code

### ISSUE THREAD

**Issue by nickrsan** [ucd-cws/arcproject-wq-processing#36]
Approach was to adjust date and time and see which one joined more records

**Comment by andybell** [comment]
Reopening this issue: might need to rethink the strategy about doing the DST adjustment automatically. Found a case where the WQ data adjusted using (DST -1) and matched perfectly with the wrong transect.

**Comment by andybell** [comment]
Added parameter to wqt_timestamp_match.main() for controlling whether or not to apply the DST adjustment. 

TODO: add checkbox controlling the DST adjustment to the arcgis tool for adding water quality to the database.
