### ISSUE TITLE
FutureWarning: convert_objects is deprecated in gain code

### ISSUE THREAD

**Issue by nickrsan** [ucd-cws/arcproject-wq-processing#45]
Hey Andy,

When running the unittest suite on my computer (pandas 0.17), I get FutureWarning: convert_objects is deprecated during one of the unittests (either ConvertType or LoadGainWQ in test_gain_unittest). It's referencing the code in wq_gain.convert_wq_dtypes:

```
def convert_wq_dtypes(df):  # TODO check to see if the wq_from_file function can do this
	"""
	Converts all the strings in dataframe into numeric (pd.to_numeric introduced in 0.17 so can't use that)
	:param df:
	:return: dataframe with columns converted to numeric
	"""
	for column in list(df.columns.values):
		if df[column].dtype == object:
			df[column] = df[column].convert_objects(convert_numeric=True)
	return df
```

It seems to not be formatting the code correctly - me-fail

The full warning is:
C:\Users\dsx.AD3\Code\arcproject-wq-processing\scripts\wq_gain.py:17: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  df[column] = df[column].convert_objects(convert_numeric=True)

It seems worth updating to a supported method to future proof it? What do you think?

**Comment by andybell** [comment]
In markdown three backticks before and after the code snippet work for code-blocks ` ``` `

**Comment by nickrsan** [comment]
Oh, haha - yup - I forgot that one backtick is for inline and three for blocks (partially because only one showed up when I clicked the code button). Thank you!

**Comment by nickrsan** [comment]
Grrr, looks like this is a version-based thing too - in pandas 0.17 it's deprecated, but in pandas 0.16.2, the resolution of pd.to_numeric(data_frame[field]) doesn't exist. So we'll need to do some version matching in the code (I have another spot doing similar work in check_and_convert_units - wqt_timestamp_match line 119). Just noting here so that we get both spots compatible with each version
