### ISSUE TITLE
Prepare code for database in single central location

### ISSUE THREAD

**Issue by nickrsan** [ucd-cws/arcproject-wq-processing#81]
Hey Andy,

I'm getting close to having a complete installer that sets up R. One thing I noticed is that the R scripts assume the database will be relative to the project root (as the classes code does), an I wanted to flag for us each that we should prep any code we have to load data from a database centralized on the X drive since I'm assuming that's where we'll move the database. My thinking is that the code, etc, can be installed on any computer, and it will know to grab the data from the X drive DB. Thoughts?

**Comment by andybell** [comment]
I just tested it out and I don't think that should be that much of an issue for R. The path to the database in the R scripts should be modified to something like `database='Z:/arcproject_z_drive/wqdb.sqlite'`.

**Comment by nickrsan** [comment]
OK, the Python code should now check for a DEV_MODE file in the project root, and when it's present, use the same logic it currently uses. Otherwise, it looks for `db_location = r"X:\ArcProject\ArcProjectData\water_quality_db.sqlite"` - going to merge your branch and then see if I can't get the R scripts to behave similarly.

**Comment by nickrsan** [comment]
Getting the R Script path (and thus finding the flag file) is non-trivial. I might try to convert the R code to a package to make that work. That's for tomorrow though.

**Comment by nickrsan** [comment]
Hey Andy,

I think I have the R code mostly working again, but I don't think I have a working combination of site/variable to get a heatplot generated. When you get a moment, can you send me the site/variable you're using for testing? Thanks!

**Comment by nickrsan** [comment]
Oh, also, I can file this separately, but I've been wondering about making the plot output location a parameter. I think the plots directory will be in an obscure location after installation, so we'll want to give them that option. Let me know if you disagree.

**Comment by nickrsan** [comment]
I think all issues in this thread should be all complete
