### ISSUE TITLE
get_r_folder() - unable to get r path

### ISSUE THREAD

**Issue by andybell** [ucd-cws/arcproject-wq-processing#82]
Getting the R folder location using winreg on my machine is not working correctly. 

Here is a screenshot of the registry editor for the r-core folder: 

![image](https://cloud.githubusercontent.com/assets/7776675/23074027/87dd130e-f505-11e6-91f9-1986698b90cb.png)

**Comment by andybell** [comment]
ignore this - I figured out what was going on when looking at the setup script error message. My R install didn't have the version number in the registry

**Comment by nickrsan** [comment]
As another note about this - I think that it should be mitigated by the installation script. The install script warns you if it can't find R in the registry and specifically tells you to make sure R is installed with the version in the registry. Hopefully that makes it a blocking moment for this issue so it's taken care of
